---
title: "Animations and Interactivity"
output: html_document
---

## JEHANGEER

## Problem 1

```{r problem_1_data,include=FALSE}

#DO NOT MODIFY THIS CHUNK
library(tidyverse)

Category <-c ("Alpha","Beta","Zeta")
City <- c("Hong Kong","London","Nairobi")

my_dat <- expand_grid(Category,City)

set.seed(84684)

my_dat$Value<-sample(1:10,9, replace = T)

```

```{r problem_1_solution,echo=FALSE,message=FALSE,warning=FALSE}
library(gganimate)
library(gifski)

p <- ggplot(my_dat,aes(x = Category, y = Value, fill = City))+
      geom_bar(stat = "identity")+
      transition_states(City)
p



```

## Problem 2

```{r problem_2_data, echo=FALSE,message=FALSE,warning=FALSE}

#####DO NOT MODIFY THIS CHUNK

Response <- c("Energize","Amazing","Great")
set.seed(9819)
Energize <- tibble(Company=rep("Energize",100), Output=rnorm(100,50,20))
set.seed(9819)
Amazing <- tibble(Company=rep("Amazing",100), Output=rnorm(100,50,10))
set.seed(9819)
Great <- tibble(Company=rep("Great",100), Output=rnorm(100,40,5))

my_dat1 <- bind_rows(Energize,Amazing,Great)



```

```{r problem_2_solution, echo=FALSE,message=FALSE,warning=FALSE}

 

library(plotly)

q <- ggplot(my_dat1, aes(x = Company, y = Output, fill = Company))+
      geom_boxplot()

my_fig <- ggplotly(q)

my_fig

```

## Problem 3

```{r problem_3_data,echo=FALSE,message=FALSE,warning=FALSE}

library(plotly)

Category1 <- seq(from=1,to=10)
Time <- seq(from=1,to=10)

dat3 <- expand_grid(Category1,Time)

set.seed(78957)
dat3$Quantity<-runif(100,0,10)

```


```{r problem_3_solution,echo=FALSE,message=FALSE,warning=FALSE}

gf <- ggplot(dat3,aes(x = Category1, y = Quantity, frame = Time))+
   geom_point()+
   geom_segment(aes(x=, xend = Category1, y=, yend = Time))+
   theme(axis.text.x=element_text(angle=90))
   
      
ggplotly(gf)      
      
         

```


